### ISSUE TITLE
(Feature Request Memo) Oracle/Para/Other codebase jobports and such.

### ISSUE THREAD

**Issue by miniusAreas** [SunsetStation/SunsetStation#116]
Just a reminder to Steamport and those nerds who are working on porting the new jobs, and some others that may be viable.

From Oraclestation:
>Blueshield
>Brig Phys
>IAA (DO NOT REPLACE LAWYER WITH IAA. Theres still a diffrence, goddamit.)
>Paramedic

From Paradise:
>Coroner (Community Aproval for it)
>Psychiatrist (Community Dissaproval for it, could get linking and work with TG Traits/Moods)
>Xenobiologist (Prevents R&D from fucking running to xenobio for muh slimes and makes them do their actual job, science)
>Mechanic (Only if parapods get ported, otherwise would work as a salesman for public spacepods and for maintaining them)

From Bay:
Pathfinder (Because mining never sticks together and dicks off into the wastes, only to die cause you were A L O N E. Would answer to the QM.)
Explorer (Would go along with the Pathfinder while exploring space / lavaland. Mines when the Pathfinder isnt here or not exploring.)

Custom requests:
Preformer (Dances, plays music, and otherwise uses fine arts to entertain the crew.)
Rename Roboticist to Electronical Engineer (Because science should, again, be doing R&D, not running to do Circuits or Nanites. Science rework will be moving the Circuitry Lab, Nanite Lab, and Robotics to the same area, and putting R&D, Toxins, EXPERIMENTOR, and the Testing Lab together. Xenobio and Viro will be on the same satalite together as Biological Sciences.)
This doesnt have to all be done, its a request and a memo to @steamp0rt and the other dude to port them today as planned.

**Comment by miniusAreas** [comment]
@Jeff-jefferson-jeffery There are plans, however, EXPERIMENTOR is just a unused room in sci and can be merged into a sciblock, like whats planned with electronics and biological.
Also, a miner leader is a great idea, because who doesnt LOVE shoving your boss into lava / a chasm / fed to walkers?

**Comment by Jeff-jefferson-jeffery** [comment]
Make strange objects work more like arts from goon because those are just better versions of the same thing.

and murdering yer boss is fun, but not for them.

**Comment by Wilchenx** [comment]
>Electronical Engineer

Its called electrician and while it covers some of the field of mechatronics https://en.wikipedia.org/wiki/Mechatronics or robotics https://en.wikipedia.org/wiki/Robotics its not enough to justify the name change for a job that mainly is focused on robots, i see no reason for the renaming

>Because science should, again, be doing R&D, not running to do Circuits or Nanites.

seeing as R&D currently is a waiting simulator i don't know what you mean by "doing R&D", other than that i see no reason for these changes

>Science rework will be moving the Circuitry Lab, Nanite Lab, and Robotics to the same area, and putting R&D, Toxins, EXPERIMENTOR, and the Testing Lab together.

testing lab is only a thing on one map buddy, experimentor will EMP everything in the area, toxins will probably leak plasma into everything else and R&D is just pressing buttons, no reasoning behind changes

>Xenobio and Viro will be on the same satalite together as Biological Sciences.

why is viro being away from medical a benefit in any way shape or form, no reasoning behind the changes

>Pathfinder (Because mining never sticks together and dicks off into the wastes, only to die cause you were A L O N E. Would answer to the QM.)
Explorer (Would go along with the Pathfinder while exploring space / lavaland. Mines when the Pathfinder isnt here or not exploring.)

these are jobs for baycode, baycode mining is vastly different from ours. There is no reason to make these changes.

**Comment by Wilchenx** [comment]
>Coroner (Community Aproval for it)

no mechanics for coroner to be a job

>Preformer (Dances, plays music, and otherwise uses fine arts to entertain the crew.)

just go assistant and do it, seems like a one time gimmick to me that doesn't justify code changes

**Comment by Wilchenx** [comment]
>job to move corpses from place to place

that's enough to justify a job?

Why not make a job for every mundane task instead of generalizing them in one job

Afaik medical doctors are supposed to clean up the bodies, or maybe even janitor.

Adding a role just to move corpses is silly.

>it prevents stupid scientists with grenades from running around the station blowing shit up.

lol you didn't even touch chemistry

>Virology is a science and also keeps all the "HOLY FUCK THIS IS DANGEROUS SO KEEP IT AWAY" shit away from "Hey come here and get healed and totally don't become the first victims of Viro's incompetence.

Biology is science, but if we follow this principle above game design, we're moving botany and chemistry to science too, just because botany can mutate plants.

>If you went to the departmental overhauls page on the forums that was explicetly linked here, you would know more on it. But you didn't, so you dont.

again that doesn't answer to me why you think those changes are beneficial to THE GAME in any way

**Comment by dapnee** [comment]
Geneticist's job is to clone and dispose of bodies. If you were to take that, you'd be taking away another thing that leaves geneticists a reason to stay in medical instead of fucking off into science and then greytide.

**Comment by miniusAreas** [comment]
BS has been merged and this is semi-stale. FR Closed.
