### ISSUE TITLE
Scrubber configuration

### ISSUE THREAD

**Issue by Crysoskis** [SunsetStation/SunsetStation#156]
Open an air alarm and go to scrubbers tab, the game then lags to a standstill. Lag dependent on scrubbers attached, the more there are present the worse the lag is.

**Comment by Wilchenx** [comment]
seems like a problem on your end

**Comment by Crysoskis** [comment]
@Wilchenx are you not able to reproduce it? my engine im working on has 16 in one network and the lag is so bad its strange to see your clicks and drags registered about a minute later

**Comment by niceping** [comment]
More vents/scrubbers in area when you trying to configure them - more lag.

Blame /tg/ and ask to optimize air alarm stuff

**Comment by alexkar598** [comment]
My guess would be its tgui attempting to load all the little checkboxes icons

**Comment by alexkar598** [comment]
This is problem with upstream,make issue there but I think it's already there
