### ISSUE TITLE
[Feature Request] Port reinforced floor sprites from /vg/

### ISSUE THREAD

**Issue by niceping** [SunsetStation/SunsetStation#160]
Because for me they just looks better

**Comment by ghost** [comment]
Pic?

**Comment by niceping** [comment]
![ss13 ru yellow circus rogue roost papa 2018-05-20 190351](https://user-images.githubusercontent.com/40269243/45923417-4a3a6600-bf20-11e8-8d7a-6644622b02fa.png)
![imperial colony nine 2018-09-23 110100](https://user-images.githubusercontent.com/40269243/45923418-4a3a6600-bf20-11e8-80b5-2fe6bcd07864.png)

(screenshot 1 - tg old
screenshot 2 - vg)

They look actually really similar, but at the same time they not so similar. So yeah, probably should call it "port old r-floor sprites" instead

**Comment by alexkar598** [comment]
made a pr,it may or may not get merged but you were listened to and this feature request is useless now.
