### ISSUE TITLE
(FUCK) Players can emote without cooldown

### ISSUE THREAD

**Issue by miniusAreas** [SunsetStation/SunsetStation#191]
During last playtest, I noticed players could literaly spam emotes without any punishment, IE, scream (x41) while brigging the clown for 5. My god, the lag this generates is stupid, let alone not being able to see shit over radio.

**Comment by ghost** [comment]
Upstream

**Comment by Wilchenx** [comment]
>let alone not being able to see shit over radio.

you only see one message x41 due to goonchat

this is not even a bug

**Comment by miniusAreas** [comment]
The issue isnt the x41.
Its the fact that a player can ctrl + v something and fucking spam it to no end

**Comment by Wilchenx** [comment]
PEBCAK

**Comment by miniusAreas** [comment]
Reported upstream at https://github.com/tgstation/tgstation/issues/41345, closing.
