### ISSUE TITLE
(Not a feature request) !!!SEND ISSUES DEALING WITH MINIUSAREAS MAPPING HERE!!!

### ISSUE THREAD

**Issue by miniusAreas** [SunsetStation/SunsetStation#194]
https://github.com/miniusAreas/SunsetStation---mA-MAPPING-DIVISION

This is to lighten the amount of issues my shitmapping may create and also help me have all the issues at a glance rather than a search and scrolling. Again, please refer any issues dealing with my mapping to the repository above, thanks.

**Comment by miniusAreas** [comment]
@alexkar598 fucking autocorrect
anyways, you get the meaning

**Comment by miniusAreas** [comment]
also, go yell at the discord team that im not avalible on discord, only git/forums, and if theres anything people pinged me about they need to shoot it at me ASAP via git

**Comment by niceping** [comment]
![sunset station rogue suffix mu 2018-09-30 082331](https://user-images.githubusercontent.com/40269243/46257395-d7b72080-c4f3-11e8-8449-1d6c91a26b92.png)
excuse me what the fuck
also i generally don't like this remapping, but will deal with that later

**Comment by miniusAreas** [comment]
@kingoftheautism Thats where the BS office that ive mapped like 30 times and accidently erased is supposed to fucking go. Its open so that when the maps get merged together it doesnt erase the BS office, hopefully.

Hoping that i finish the issues with disposals piping in brig, MULEbots, and several other issues including lighting and items over crates, today.

**Comment by alexkar598** [comment]
With the mapping being dead due to lack of author im going to close this.
