### ISSUE TITLE
#3 - Crusher Voucher no longer gives a mining webbing.

### ISSUE THREAD

**Issue by miniusAreas** [SunsetStation/SunsetStation#27]
Using your mining voucher for the crusher kit no longer gives a Explorers Webbing. This makes paying mining with the crusher almost impossible without having to pull something other than a mining box, or dropping your scanner.

We had this on oracle, but not sure why TG discluded it.

**Comment by alexkar598** [comment]
Made mining packs unbalanced and worth too much,they are pretty much crap tbh now tho

**Comment by alexkar598** [comment]
went ahead and added this to the unconfirmed area of oracle station porting project,issues should be for issues,not features requests
