### ISSUE TITLE
Telescopic Batons can keep people in a stunlock.

### ISSUE THREAD

**Issue by miniusAreas** [SunsetStation/SunsetStation#28]
The cooldown on the batons stun is so short that its fully possible to keep someone permanently in a stunlock. Heads of Staff shouldnt have this power, they dont need to be validhunting. This also makes it as good as a stunbaton when keeping someone down.

**Comment by alexkar598** [comment]
Feature request,not too sure if its allowed @sunsetstation12

**Comment by miniusAreas** [comment]
@alexkar598 Not so, the stuntimes and our station time are diffrent, and IIRC cooldowns are based on station time, so its fully possible they are ment for TGs methspeed

**Comment by miniusAreas** [comment]
Not having a stun indicator doesnt help either.

**Comment by alexkar598** [comment]
Since this seems to be a bug,im going to keep it open,will need reproducing however

**Comment by miniusAreas** [comment]
Ah, that would make more sence. We should still change the cooldown so that they are not abused.

**Comment by alexkar598** [comment]
This was moved to github projects
https://github.com/SunsetStation/SunsetStation/projects/4
