### ISSUE TITLE
[Suggestion] Port spess pods

### ISSUE THREAD

**Issue by niceping** [SunsetStation/SunsetStation#319]
Why: Since we have Oracle move speed, exploring space can be a little bit difficult (especially since /tg/ removed flight suit), so we can port space pods.

Possible functionality:
mining tools, for, you know, mining stuff, and flying above lava.
combat stuff, for bullying space carps and people in space.
civilian stuff, like simple engine booster to make space pod fly faster

Possible functions:
Miners - can fly above lava, high speed, kind of like mech but locals can still bully them since space pods barely armored
Security - chasing criminal scums without being worry about being tase'd and laser'd
Everyone else - fuck around in space

Possible styles:
Goon pods - 1 tile pods, not so fast
VG pods - 2x2 tile pods, fast as fuck

**Comment by alexkar598** [comment]
@steamp0rt you should be able to make a PR for it by memory now

**Comment by ghost** [comment]
no. we're waiting for @ninjanomnom to do pixel movement on /tg/

**Comment by miniusAreas** [comment]
@steamp0rt w h y, pixel movement is rather bad and frustrating, is it possible to do it without it?

**Comment by ghost** [comment]
It makes multi tile objects much better

**Comment by miniusAreas** [comment]
@steamp0rt https://github.com/ParadiseSS13/Paradise/pull/631

How does it make them better, enrich me and my git-dumb brain.

**Comment by ghost** [comment]
Because most things aren't coded to expect a single object to be 2x2

**Comment by alexkar598** [comment]
This was moved to github projects https://github.com/SunsetStation/SunsetStation/projects/4
