### ISSUE TITLE
(Bug) Blueshield rolled traitor

### ISSUE THREAD

**Issue by Scarpy** [SunsetStation/SunsetStation#324]
Blueshield somehow rolled traitor and spawned inside Virology, not being able to get out of there.

@steamp0rt

**Comment by niceping** [comment]
Normally, all roles with mindshield implants (captain, sec, etc) are "secured" type, and cannot role traitor (except for badminnery), so it can probably be badminnery, or someone just fucked it up.

About blueshield spawning in Viro - who knows, maybe there was no blueshield spawning point at all so he rolled randomly and spawned there, I dunno

**Comment by alexkar598** [comment]
For the spawn point part,I didn't want to conflict the other mapping PR so I didn't gave him a spawn point but for the traitor part,that's a bug I'm going to have to fix

**Comment by miniusAreas** [comment]
@Scarpy This is a config change that @SunsetStationuser needs to config, along with non-human command. @steamp0rt Not a bug. @alexkar598 Im working as fast as my shitternet will go, please hold.

**Comment by alexkar598** [comment]
This is a config issue so this is TECHNICALLY a feature request.

**Comment by alexkar598** [comment]
Config got fixed btw
