### ISSUE TITLE
The End.

### ISSUE THREAD

**Issue by miniusAreas** [SunsetStation/SunsetStation#362]
Well, it finally happened.

All support for my departmental overhauls and any map edits are no longer supported by me.

why - My computer, a HP stream, has finally shit its last breath. It is fully broken, cant even run it anymore after i took it apart and ran it bare-bones.

Whys this important for the git?
My mapping idea was great. I also have no way of getting on the discord to tell @steamp0rt. @alexkar598, or anyone else, lest to continue mapping. (Chromebooks dont have BYOND mapping support and i cant get to the website - if you can get ss13 to run on a chromebook, gitmessage me ASAP please) If you get this, please. Finish it so that I may always have a piece of sunset with me always. I may never see the server come to, or be able to play ss13 with the way my income is. And someone go to discord.gg/rimworld and ping a mod telling them that my PC shit itself, me being Kirov.

Anyways, so long sunset. We had a good run, but the days of joy are gonna be filled with a empty void, and shitty flash games.

- mA
(PS, FLATTEST IS A NERD :p)

**Comment by Crysoskis** [comment]
and you didnt try to take the hard drive out and recover data or was it the hard drive that crapped

**Comment by miniusAreas** [comment]
@Crysoskis its a built in drive to the microATX motherboard. The original issue is that the CPU was overheating and going into a failsafe mode to prevent damage. However, i began to use freezerpacks to cool the small heatsink, and from there um, the heatsink melted some shit and it simply wont work, im using a school chromebook.

**Comment by Crysoskis** [comment]
show me a picture of the board if you can, or a picture of the drive online

**Comment by miniusAreas** [comment]
1, impossible to take pictures with a chromebook and i aint got a phone, two i have no fucking clue where the drive even is.

**Comment by Crysoskis** [comment]
can you find a label of the name on the board and send that, also i figured you had a smartphone but i guess not

**Comment by Crysoskis** [comment]
i work in IT, diagnosing and finding solutions to this kinda stuff is my living

**Comment by Crysoskis** [comment]
you want to move this to a discord dm instead

**Comment by alexkar598** [comment]
I dunno what your allowed to do on your chrome book/ what you can do since its a school chrome book but IIRC it is possible to root a chrome book,install wine and install byond to play ss13 bc at the base chromeos is like macos and iOS,it's a version of Linux made for grandmas by locking away everything that makes Linux complex

**Comment by ghost** [comment]
~~yeah, you can dualboot on chromebooks~~

~~[go into developer mode](https://www.howtogeek.com/210817/how-to-enable-developer-mode-on-your-chromebook/), [download a GalliumOS iso, ](https://galliumos.org/), [`dd` it to a USB stick....](https://superuser.com/questions/351814/how-to-copy-an-iso-image-onto-usb-with-dd#351815), then....~~

~~you need to flash SeaBIOS: https://mrchromebox.tech/#fwscript (Install/Update RW_LEGACY Firmware)~~

~~then you can boot from the USB and install GalliumOS, and run BYOND via Wine.~~

nvm you probably can't do this on a school chromebook

**Comment by ghost** [comment]
why is this an issue report

**Comment by alexkar598** [comment]
Okay use discord for stuff like that next time
